repos:
  - repo: https://github.com/vdmitriyev/latex-git-hooks
    rev: v0.2.0  # Use the latest version
    hooks:
    - id: check-latex-packages
    - id: ignore-auxiliary-files
    - id: no-space-in-cite
    - id: no-space-in-citep
    - id: comma-in-eg-ie
    - id: check-single-command-per-line
    - id: run-linter-paperlinter
